_target_: nerf_utils.renderer.renderer_eg3d.Efficient3dRadianceFieldRenderer
# gpen configs
narrow: 0.25
channel_multiplier: 1
isconcat: True
lr_mlp: 0.01
blur_kernel: [1,3,3,1]
n_mlp: 8
style_dim: 512
audio_dim: 464
norm_momentum: 0.1
tri_plane_sizes: [128]
