train: True
test: False
seed: 3

stats_print_interval: 100
validation_epoch_interval: 1
checkpoint_epoch_interval: 1

precache_rays: True
engine: eg3d_engine
device: cuda #cpu

# checkpoints
resume: False
checkpoint_dir: 'checkpoints'
resume_from: 'latest_model.pth'

# special characters
nosmo_epoches: 1000000 # -1
smo_size: 8

# loss terms 
losses:
  gan: 0
  l1: 100
  percept: 0
  id: 0

defaults:
  - _self_
  - data: obama_batch # basic
  - renderer: eg3d
  - test: evaluation_basic
  - visualization: port_eg3d
  - raysampler: eg3d
  - optimizer: adam_lambda_eg3d
  - validation: basic
  - components: eg3d
