n_harmonic_functions_xyz: 10
n_harmonic_functions_dir: 4
n_hidden_neurons_xyz: 256
n_hidden_neurons_dir: 128
density_noise_std: 0.0
n_layers_xyz: 8
transparent_init: False
return_feat: True
dim_aud: 64
seq_len: 16
render_size: [64, 64]
